### ISSUE TITLE
Add option to set environment variables

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-tester-plugin#3]
This would make easier use the plugin. For example:

https://github.com/boundlessgeo/qgis-geogiglight-plugin/blob/master/geogig/tests/__init__.py

REPOS_SERVER_URL = "http://localhost:8182/"
REPOS_FOLDER = "d:\\repo" #fill this with your repos folder

as far as I understand this variables need to be set manually.

**Comment by alexbruy** [comment]
Should be fixed in d22e61c6dd

**Comment by gioman** [comment]
> Should be fixed in d22e61c

@volaya @alexbruy I have:

geogig
Installed version: 1.0-201610041315-3E0A08F 

tester:
Installed version: 0.1-201610041103-473DAE8

I still not see anything different from previous versions.

**Comment by gioman** [comment]
> Should be fixed in d22e61c

yes but https://github.com/boundlessgeo/qgis-tester-plugin/issues/10
